### ISSUE TITLE
LuteBot seemingly randomly skips notes during playback

### ISSUE THREAD

**Issue by ArmokGoB** [Dimencia/LuteBot3#13]
It's hard to tell if the commands are being sent to the game or not, but certain notes are skipped on certain MIDIs. I think it's has a higher chance of happening with "busy" songs, but even on relatively light songs (_Toss a Coin to Your Witcher_ and _Big Iron_, for example) there is a tendency to skip notes.

**Comment by Dimencia** [comment]
LuteBot (and LuteMod) has to skip some notes to work correctly with Mordhau's time limits (16ms per note command in LuteMod, longer in LuteBot)

More recent releases might work better, especially in LuteMod, because it uses a new algorithm to determine the best notes to prioritize if it has to skip some.  I know this is a very old issue and you're probably already on lutemod, but at this point I am no longer interested in improving lutebot playback anyway, so I'm gonna go ahead and close it
